
{block content}

<script type="text/javascript" src="{$baseUri}/js/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<link href="{$baseUri}/css/jquery/jquery-ui-1.8.9.custom.css" rel="stylesheet" type="text/css" media="all" />
<link href="{$baseUri}/css/gridito.css" rel="stylesheet" type="text/css" media="all" />



<script type="text/javascript" src="{$baseUri}/js/jquery.livequery.js"></script>
<script type="text/javascript" src="{$baseUri}/js/jquery.ui.gridito.js"></script>
<script type="text/javascript" src="{$baseUri}/js/function.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $("div.gridito").livequery(function () {
            $(this).gridito();
        });

        // nette ajax init
        $("a.ajax").live("click", function (event) {
            //alert(this.href);
            event.preventDefault();
            $.get(this.href);
        });

        $(function() {
		$( "button, input:submit, a", ".buttonUi" ).button();
		//$( "a", ".demo" ).click(function() { return false; });
	});
    });

</script>
<div id="sidebar">
            <h2 class="style2">Detail</h2>
</div>
<br /><br /><br /><br /><br /><br />
{if $editPermission !== null}
{control gridConcurrency}<br />
<div class="buttonUi">
    <a n:href="default, $id">Zpět</a>
</div>
{else}
                <div class="buttonUi">
                    <a href="{plink :Admin:Seo:Homepage:default}" >Zpet</a>
                </div><br />
                <p>Nemáte práva pro prohlížení stránky!</p>
{/if}