{block #content}

<script type="text/javascript">
    $(document).ready(function() {
        $("#frmlogin-login").click(function(event) {
            $(".rules").text("");
        });
    });
</script>

<!-- Main -->
<div id="main">
	<div class="shell">

		<!-- Cols -->
		<div class="cols">
			<div class="cl">&nbsp;</div>

			<!-- Col -->
			<div class="col">
				<h3>Sed Turpis sem</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam arcu ligula, faucibus eu imperdiet eu, bibendum sit amet augue. Sed turpis sem, interdum sit amet egestas a, mattis non libero.<br /><a href="#" class="more">read more</a></p>
				<p>Suspendisse tristique nisi sed justo accumsan vel mattis nulla fermentum. Etiam varius est id mi fermentum aliquam. <br /><a href="#" class="more">read more</a></p>
			</div>
			<!-- End Col -->

			<!-- Col -->
			<div class="col">
				<h3>Ligula amet augue</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam arcu ligula, faucibus eu imperdiet eu, bibendum sit amet augue. <br /><a href="#" class="more">read more</a></p>
				<p>Sed turpis sem, interdum sit amet egestas a, mattis non libero. Suspendisse tristique nisi sed justo accumsan vel mattis nulla fermentum. Etiam varius est id mi fermentum aliquam. <br /><a href="#" class="more">read more</a></p>
			</div>
			<!-- End Col -->

			<!-- Col -->
			<div class="col col-last">
                                
				<h3>Přihlášení:</h3>
                                <div class="rules"></div>
				<p>{control login}</p>
                                <p><a n:href="Registrace:Registrace:default">Zaregistrujte se</a></p>
			</div>
			<!-- End Col -->

			<div class="cl">&nbsp;</div>
		</div>
		<!-- End Cols -->

	</div>
</div>
<!-- End Main -->