{block #content}
<script type="text/javascript" src="{$baseUri}/js/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<link href="{$baseUri}/css/jquery/jquery-ui-1.8.9.custom.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript">


        $(function() {
		$( "button, input:submit, a", ".buttonUi" ).button();
	})
</script>

<div id="content">
<h2>O nás</h2>
<p>Tento projekt vznikl jako bakalářské práce, které jsou dostupné společně pod jedním uživatelským účtem.</p>
<h3>Nástroj pro validaci internetových stránek pro SEO a SEM</h3>
<p>Vypracoval: Petr Čmela</p>

<div class="buttonUi"><a n:href=":Front:Homepage:seo">Zpět</a></div>
</div>