{block content}
<div id="content">
<h2>SEO a SEM</h2>
<h3>Kontrola pozic ve vzhledávačích</h3>
<p>Nástroj pro kontrolu pozic ve vzhledávačích Vám může ušetřit spoustu času. Namísto pracného vyhledávání a zjišťování pozic v každém fulltextovém
vyhledávači ručně, stačí zadat Vaší internetovou stránku, přidat k ní důležitá klíčová slova a pravidelně aktualizovat statistiky.</p>
<p class="more"><a n:href=":Front:Homepage:check-position">Více zde</a></p>

<h3>Napovídání klíčových slov</h3>
<p>Nástroj umožňuje zjištění příbuzných slov, slovu zadanému a tím zajistit long tail internetové stránky.</p>
<p class="more"><a n:href=":Front:Homepage:find-keywords">Více zde</a></p>

<h3>Zjišťování konkurence</h3>
<p>Na základě výsledků pozic jednotlivých klíčových slov přiřazených k internetové stránce, je možné zjistit případnou konkurenci,
která se ve vyhledávačích objevuje na stejná slova jako Vaše stránka.</p>
<p class="more"><a n:href=":Front:Homepage:concurrency">Více zde</a></p>

<h3>Kontrola on-page faktorů stránky</h3>
<p>Jako jeden z dalších nástrojů lze využít kontrolu on-page faktorů stránky. Kontrola Vám zjistí zda stránka dodržuje základní pravidla zdrojového kódu,
která Vám mohou pomoci k lepšímu hodnocení vyhledávači.</p>
<p class="more"><a n:href=":Front:Homepage:on-page-factors">Více zde</a></p>

<h3>Zjišťování ranků internetové stránky</h3>
<p>Pro zjištění SRanku, Alexa ranku, Google Page Ranku atd. slouží nástroj pro zjišťování ranků stránky.</p>
<p class="more"><a n:href=":Front:Homepage:ranks">Více zde</a></p>

<h3>Konkurence</h3>
<p>Ke každé přidané internetové stránce, lze přidat weby konkurence. S weby konkurence pak můžete porovnávat Vaší stránku pomocí celkové analýzy pozic
ve vyhledávačích, nebo sledovat pozice každého konkurenčního webu.</p>
<p class="more"><a n:href=":Front:Homepage:concurrency-view">Více zde</a></p>

<h3>Celková analýza</h3>
<p>Celková analýza provádí na porovnání srovnání Vašeho webu s weby konkurenčními. Data jsou vykresleny do grafů a je na nich znázorněno, který web
má celkově lepší pozice ve výsledcích vyhledávačů.</p>
<p class="more"><a n:href=":Front:Homepage:over-all">Více zde</a></p>

</div>