
{block content}
<script type="text/javascript">
$(document).ready(function(){   
        $(function() {
		$( "button, input:submit, a", ".buttonUi" ).button();
	});

         $("#frm-userForm").submit(function(event) {
            $(".rules").text("");
        });
 });
 </script>
<script type="text/javascript" src="{$baseUri}/js/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<link href="{$baseUri}/css/jquery/jquery-ui-1.8.9.custom.css" rel="stylesheet" type="text/css" media="all" />

<div id="content">
    <div n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>
    <div class="buttonUi"><a n:href=":Admin:Homepage:default">Zpět</a></div>

    <div class="rules"></div>
    {control userForm}

</div>