{block content}

<div id="sidebar">
    <h2 class="style2">Menu</h2>
    {cache}
    <h3>Administrace stránek</h3>
    <p><a href="{link :Admin:Seo:Homepage:addWeb}">Přidat stránku</a></p><br />

    <p><a href="{link :Admin:Seo:Homepage:addPermission}">Přidat oprávnění</a></p>
    <p><a href="{link :Admin:Seo:Homepage:checkPermission}">Zkontrolovat oprávnění</a></p><br />

    <h3>Administrace oprávnění</h3>
    <p><a href="{link :Admin:Seo:Ranky:Check:default}">Zkontrolovat ranky</a></p>
    <p><a href="{link :Admin:Seo:OnPageFactors:Check:default}">Zkontrolovat Stránku</a></p><br />

    {/cache}

</div>