<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{$baseUri}/css/default.css" rel="stylesheet" type="text/css" media="all" />
<style type="text/css">
@import "layout.css";
</style>
</head>
<body>
<div id="header">
	<div id="logo">
		<h1><a href="/seoBc_layout_copy/document_root/">Business Name</a></h1>
		<p>Lorem Ipsum Veroeros</p>
	</div>
	<div id="menu">
		<ul>
			<li class="first"><a href="#" accesskey="1" title="">Products</a></li>
			<li><a href="#" accesskey="2" title="">Services</a></li>
			<li><a href="#" accesskey="3" title="">Clients</a></li>
			<li><a href="#" accesskey="4" title="">Support</a></li>
			<li><a href="#" accesskey="5" title="">About</a></li>
			<li><a href="#" accesskey="6" title="">Careers</a></li>
			<li><a href="#" accesskey="7" title="">Contact</a></li>
		</ul>
	</div>
</div>
<!-- end #header -->
<div id="page">
	<div id="content">
		<p style="margin-bottom: 30px;"><a href="#"><img src="images/homepage08.jpg" alt="" width="530" height="156" /></a></p>
		<h2 class="style1">Magna Libero Dolor</h2>
		<h3>Sed nullam veroeros blandit</h3>
		<img src="images/homepage09.jpg" alt="" width="115" height="105" class="alignleft" />
		<p>Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo id, eleifend. Lorem ipsum consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo id, eleifend.</p>
		<p class="more"><a href="#">Learn more&hellip;</a></p>
	</div>
	<!-- end #content -->
	<div id="sidebar">
		<h2 class="style2">Veroeros Blandit</h2>
		<img src="images/homepage10.jpg" alt="" width="95" height="113" class="alignleft nopad" />
		<p>Cras vitae felis eget mi laoreet cursus. Nunc vehicula est ac sem. Sed mollis consequat dolore.</p>
		<p class="more"><a href="#">Learn more&hellip;</a></p>
		<p>&nbsp;</p>
		<img src="images/homepage11.jpg" alt="" width="95" height="108" class="alignleft nopad" />
		<p>Cras vitae felis eget mi laoreet cursus. Nunc vehicula est ac sem. Sed mollis consequat dolore.</p>
		<p class="more"><a href="#">Learn more&hellip;</a></p>
		<p>&nbsp;</p>
		<img src="images/homepage12.jpg" alt="" width="95" height="108" class="alignleft nopad" />
		<p>Cras vitae felis eget mi laoreet cursus. Nunc vehicula est ac sem. Sed mollis consequat dolore.</p>
		<p class="more"><a href="#">Learn more&hellip;</a></p>
	</div>
	<!-- end #sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end #page -->
<div id="box1">
	<div class="wrapper">
		<h2>Vehicula Lorem</h2>
		<h3>Sed nullam consequat etiam</h3>
		<div class="column1"> <img src="images/homepage15.jpg" alt="" width="105" height="105" class="alignleft" />
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo id, eleifend. Lorem ipsum dolor sit amet nullam veroeros blandit lorem.</p>
			<p class="more"><a href="#">Learn more&hellip;</a></p>
		</div>
		<div class="column2"> <img src="images/homepage16.jpg" alt="" width="105" height="105" class="alignleft" />
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo id, eleifend. Lorem ipsum dolor sit amet nullam veroeros blandit lorem.</p>
			<p class="more"><a href="#">Learn more&hellip;</a></p>
		</div>
		<div style="clear: both;">&nbsp;</div>
	</div>
</div>
<!-- end #box1 -->
<div id="box2">
	<div class="wrapper"> <img src="images/homepage17.jpg" alt="" width="116" height="116" class="alignleft" />
		<h2>Consectetuer magna tempus?</h2>
		<h3>Eleifend lorem ipsum nullam veroeros dolor</h3>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo id, eleifend. Lorem ipsum dolor sit amet nullam <a href="#">veroeros blandit lorem</a>. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque tincidunt auctor mauris. Duis magna are Nam mi velit, commodo  ipsum dolor sit <a href="#">amet nullam veroeros</a> blandit lorem.</p>
	</div>
</div>
<!-- end #box2 -->
<div id="footer">
	<p>Copyright (c) 2008 BusinessName. All rights reserved.</p>
</div>
<!-- end #footer -->
</body>
</html>