
{block content}
<script type="text/javascript" src="{$baseUri}/js/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<link href="{$baseUri}/css/jquery/jquery-ui-1.8.9.custom.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{$baseUri}/js/validation.js"></script>
<script type="text/javascript">

$(document).ready(function(){
        $(function() {
		$( "button, input:submit, a", ".buttonUi" ).button();
	});

        
            $("#frm-webForm").submit(function(event) {
                $(".rules").text("");
                    var p = document.forms['frm-webForm'];
                    if(validate(p['frmwebForm-url'].value)){
                        $( "#dialog:ui-dialog" ).dialog( "destroy" );

                            $( "#dialog-modal" ).dialog({
                                    height: 140,
                                    modal: true,
                                    closeOnEscape: false,
                                    open: function(event, ui) { $(".ui-dialog-titlebar-close").hide(); }

                            });
                    }

            });
       

});
</script>

<div id="dialog-modal" title="Požadavek se zpracovává">
	<p>Počkejte prosím, probíhá zpracování dat.</p>
</div>
<style type="text/css">
    #dialog-modal{
        display: none;
    }
</style>

<div id="content">
    <div class="buttonUi"><a n:href=":Front:Homepage:servicesView">Zpět</a></div>

    <div class="rules"></div>
    {control webForm}

    {if $submit}
    <h3>Ranky:</h3>
    <ul class="resultBox">
        <li class="info">PageRank: {$pageRank}/10</li>
        <li class="info">SRank: {$sRank}</li>
        <li class="info">AlexaRank: {$alexaRank}</li>
    </ul><br />

    <h3>Zpětné odkazy:</h3>
    <ul class="resultBox">
        <li class="info">Zpětné odkazy na stránku: {$backlinks}</li>
    </ul><br />

    <h3>Popularita webu:</h3>
    <ul class="resultBox">
        <li class="info">Seznam: {$seznamPopularity}</li>
        <li class="info">Google: {$googlePopularity}</li>
        <li class="info">Bing: {$bingPopularity}</li>
    </ul><br />

    <h3>Indexované stránky webu:</h3>
    <ul class="resultBox">
        <li class="info">Seznam: {$seznamIndexPages}</li>
        <li class="info">Google: {$googleIndexPages}</li>
        <li class="info">Bing: {$bingIndexPages}</li>
    </ul><br />

    <h3>Ostatní:</h3>
    <ul class="resultBox">
        {if $age !== null}
        <li class="info">Stáří webu je: {$age} měsíců.</li>
        {else}
        <li class="info">Doména nemá žádný záznam ve webarchive.org.</li>
        {/if}
        <li class="info">Počet záznamů na wikipedia.org: {$wikiBackLinks}</li>
    </ul><br />
    {/if}
</div>